apiVersion: batch/v1
kind: Job
metadata:
  name: bronze-layer-job
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: bronze
        image: creditbronzeeacr.azurecr.io/bronze:latest
        env:
        - name: AZURE_STORAGE_ACCOUNT
          value: "credit_storage_bronze"
        - name: AZURE_STORAGE_KEY
          valueFrom:
            secretKeyRef:
              name: azure-secret
              key: azure-storage-key
      restartPolicy: Never
  backoffLimit: 4
