apiVersion: batch/v1
kind: Job
metadata:
  name: gold-layer-job
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: gold
        image: creditsilvereacr.azurecr.io/gold:latest
        env:
        - name: AZURE_STORAGE_ACCOUNT
          value: "credit_storage_silver"
        - name: AZURE_STORAGE_KEY
          valueFrom:
            secretKeyRef:
              name: azure-secret
              key: azure-storage-key
      restartPolicy: Never
  backoffLimit: 4
