name: CI and CD Pipeline for credit lending

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: creditlending.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push Bronze layer image
      run: |
        docker build -t creditbronzeacr.azurecr.io/bronze:latest ./docker_image/bronze
        docker push creditbronzeacr.azurecr.io/bronze:latest

    - name: Build and push Silver layer image
      run: |
        docker build -t creditsilvereacr.azurecr.io/silver:latest ./docker_image/silver
        docker push creditsilvereacr.azurecr.io/silver:latest

    - name: Build and push Gold layer image
      run: |
        docker build -t creditgoldacr.azurecr.io/gold:latest ./docker_image/gold
        docker push creditgoldacr.azurecr.io/gold:latest

    - name: Deploy to AKS
      uses: azure/aks-set-context@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        cluster-name: myAKSCluster
        resource-group: myResourceGroup

    - name: Apply Kubernetes services
      run: |
        kubectl apply -f kubernetes/bronze_spark_job.yaml
        kubectl apply -f kubernetes/silver_spark_job.yaml
        kubectl apply -f kubernetes/gold_spark_job.yaml
